camera_config_parameters:
  deviceID: 0
  width: 1080
  height: 1920
  brightness: 150
  contrast: 100
  saturation: 100
  hue: 0
  exposure: 0

camera_inside_parameters:
  focal_length: 3.6
  sensor_width: 4.8
  sensor_height: 3.6

camera_physical_pose:
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    offset: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

map_config_parameters:
  map_name: "RMUC_2026_Lite"
  obj_map_file_path: "data/Mapdata/map_obj/RMUC_2026_MAP.obj"
  bin_map_file_path: "data/Mapdata/map_bin/RMUC_2026_MAP.bin"

game_config_parameters:
  game_state: "preparation"
  game_side:
    enemy: "red"
    ally: "blue"
  version: "test"

# version could be choosen from test and release
# test version used video to test the algorithm, release version used real-time data from camera, and the data will be sent to the robot through serial port.
